name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.4.4"

    - uses: oven-sh/setup-bun@v2

    - name: Build bstdlib
      run: |
        bun ./macro.ts bstd.lua bstdduck.lua -DNO_FILESYSTEM

    - name: Test bstdlib
      run: |
        lua test.lua
    
    - uses: actions/upload-artifact@v4
      with:
        name: bstd.lua
        path: bstdduck.lua
        if-no-files-found: warn
        retention-days: 5

